//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarnProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animals()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int AnimalId { get; set; }
        public string AnimalSpecies { get; set; }
        public Nullable<int> AnimalAge { get; set; }
        public string AnimalGender { get; set; }
        public Nullable<int> AnimalLifePeriod { get; set; }
        public Nullable<decimal> AnimalPrice { get; set; }
        public string AnimalProduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
